import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Banner from "./shared/banner";
import { Suspense } from "react";
import Loading from "./shared/banner/loading";
import Nav from "./shared/nav";
import { clsx } from "clsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={
          clsx([geistSans.variable, geistMono.variable, 'antialiased'])}
      >
        <div>
          <Suspense fallback={<Loading />}>
            <Banner />
          </Suspense>
          <Nav />
          <div className="relative -z-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
